spring.application.name=audiostore
spring.data.mongodb.database=audiostore
spring.data.mongodb.uri=mongodb://localhost:27017/audiostore
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
upload.directory=src/main/resources/static/uploads/
